name: "Docker Build and Scan"
description: "Composite action for docker build and scan"

inputs:
  image_env:
    description: 'Docker image environment. ex: dev'
    required: true
  DOCKER_USER: 
    description: 'Docker registry login username'
    required: true
  DOCKER_PASSWD: 
    description: 'Docker registry login  password'
    required: true
    
outputs:
  deploy_image:
    description: "Deployment image"
    value: ${{ steps.docker.outputs.image1 }}

runs:
  using: "composite"
  steps:
    - name: Build Docker Image
      shell: cmd
      run: |  
        set image_prefix=$np_registry/$service_name         
        docker build -t lowerupper:latest .
        
    - name: Publish Docker Image
      shell: cmd
      id: docker
      run: | 
        #registry_url=$(echo $image1 | cut -d / -f 1 )
        #echo ${{ inputs.DOCKER_PASSWD }} | docker login $registry_url -u ${{ inputs.DOCKER_USER }} --password-stdin
        docker login 192.168.1.41:8083 -u ${{ inputs.DOCKER_USER }}  -p  ${{ inputs.DOCKER_PASSWD }}    
        docker image push  lowerupper:latest ; 
