name: "Docker Build and Scan"
description: "Composite action for docker build and scan"

inputs:
  image_env:
    description: 'Docker image environment. ex: dev'
    required: true
  DOCKER_USER: 
    description: 'Docker registry login username'
    required: true
  DOCKER_PASSWD: 
    description: 'Docker registry login  password'
    required: true
    
outputs:
  deploy_image:
    description: "Deployment image"
    value: ${{ steps.docker.outputs.image1 }}

runs:
  using: "composite"
  steps:
    - name: Build Docker Image
      shell: cmd
      run: |  
        set image_prefix=$np_registry/$service_name         
        docker build -t lowerupper:latest .
        
    - name: Publish Docker Image
      shell: cmd
      id: docker
      run: | 
        docker login -u ${{ inputs.DOCKER_USER }}  -p  ${{ inputs.DOCKER_PASSWD }} http://192.168.1.39:8083/repository/docker-hosted/
        docker tag lowerupper:1.0.91 192.168.1.39:8083/docker-hosted/lowerupper:latest
        docker push 192.168.1.39:8083/docker-hosted/lowerupper:latest 
