name: lowerupper-gha
on:
  push:
    branches:
      - test
      - temp2
env:
  registry_url: 192.168.1.41:8083
  config_repository: https://github.com/saurabhsharmaj/lowerupper-gha-config.git
permissions:
  contents: write
jobs:
  deploy:
    environment: Dev
    runs-on: ['self-hosted', 'windows', 'X64', 'onprem', 'devops']
    steps:
      - uses: actions/checkout@v4

      - name: Set NEW_TAG environment variable
        run: echo "NEW_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install Docker
        run: |
          #sudo yum install -y yum-utils   ## device-mapper-persistent-data lvm2
          #sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          #sudo yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
          #sudo systemctl restart docker.service
          #sudo systemctl enable docker.service
          #sudo systemctl status docker.service

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          #otlp_url: ${{ vars.OTLP_ENDPOINT }}
          #VAULT_CONFIG_SERVR_URL:  ${{ vars.VAULT_CONFIG_SERVR_URL }}
          java-version: 17
          distribution: 'adopt'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true
      
      - name: Docker build and scan
        uses: ./.github/actions/docker_build  
        id: docker      
        with:
          image_env: dev                                        #this will be added as prefix to the image tag
          #otlp_url: ${{ vars.OTLP_ENDPOINT }}
          #VAULT_CONFIG_SERVR_URL:  ${{ vars.VAULT_CONFIG_SERVR_URL }}
          #OTLP_PROTOCOL: ${{ vars.OTLP_PROTOCOL }}
          #PRISMACLOUD_USER: ${{ secrets.PRISMACLOUD_USER }}
          #PRISMACLOUD_PASSWD: ${{ secrets.PRISMACLOUD_PASSWD }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
      
      - name: Build Docker Image
        run: |
          sudo docker build -t ${{ env.registry_url }}/docker-hosted:${{ env.NEW_TAG }} .

      - name: Push Docker image to Nexus
        run: |
          docker login ${{ env.registry_url }} -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWD }}
          docker push ${{ env.registry_url }}/docker-hosted:${{ env.NEW_TAG }}

      - name: Update Image tag
        shell: bash
        run: |    
          git clone https://${{ secrets.TOKEN_GITHUB }}@github.com/${{ env.config_repository }}
          manifests_folder=lowerupper-gha-config/lowerupper-gha/qa
          [[ -d $manifests_folder ]] && cd $manifests_folder && kustomize edit set image ${{ env.registry_url }}/docker-hosted:${{ env.NEW_TAG }} || ( echo "$manifests_folder not found .." && exit 1 )
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://$TOKEN_GITHUB@github.com/${{ env.config_repository }}
          git commit -a -m "GHA Commit for service: version env: dev" || echo "nothing to commit !!"
          git push https://${{ secrets.TOKEN_GITHUB }}@github.com/${{ env.config_repository }} main
